services:
  camunda:
    image: camunda/camunda-bpm-platform:latest
    container_name: camunda-bpm
    ports:
      - "8080:8080"
    networks:
      - ${NETWORK_NAME}

networks:
  bpmn-network:
    driver: bridge
